os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "8.4.0"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run check
  - npm run start & sleep 20; npm run test-pa11y;
notifications:
  email: false
  webhooks:
    on_success: change
    on_failure: always
    on_start: false
before_deploy:
  - npm run build:prod
deploy:
  provider: surge
  project: ./dist/
  domain: odk-form-builder.surge.sh
  skip_cleanup: true
